create database QLKS
go
use QLKS
go
create table tbl_nhanvien
(
	MANHANVIEN nvarchar(10) primary key ,
	TENNHANVIEN NVARCHAR(100),
	SODIENTHOAI CHAR(15),
	DIACHI NVARCHAR(200),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
)
create table tbl_taikhoan
(
	USENAME NVARCHAR(50) PRIMARY KEY,
	PASS NVARCHAR (20),
	MANHANVIEN NVARCHAR(10),
	FOREIGN KEY (MANHANVIEN) REFERENCES tbl_nhanvien(MANHANVIEN)
)

GO
CREATE TABLE tbl_khachhang
(
	MAKHACHHANG nVARCHAR(10) PRIMARY KEY,
	TENKHACHHANG NVARCHAR(200),
	SODIENTHOAI CHAR(15)UNIQUE,
	SOCMND CHAR(10) UNIQUE,
	DIACHI NVARCHAR(200),
	GIOITINH NVARCHAR(10),
)
GO
CREATE TABLE tbl_dichvu
(
	MADICHVU nVARCHAR(10) PRIMARY KEY,
	TENDICHVU NVARCHAR(200),
	DONVITINH NVARCHAR(15),
	GIA MONEY,
)
GO
CREATE TABLE tbl_phong
(
	MAPHONG nVARCHAR(10) PRIMARY KEY,
	LOAIPHONG NVARCHAR(100),
	GIAPHONG MONEY,
	DONVITINH NVARCHAR(10) DEFAULT N'Ngày',
	TINHTRANG NVARCHAR(50) 
	
)
GO
CREATE TABLE tbl_phieuthuephong
(
	MAPHIEUTHUE nVARCHAR(10) PRIMARY KEY,
	MANHANVIEN nVARCHAR(10),
	MAKHACHHANG nVARCHAR(10),
	NGAYDEN DATE,
	NGAYDI DATE,
	MAPHONG nVARCHAR(10),
	FOREIGN KEY (MAKHACHHANG) REFERENCES tbl_khachhang(MAKHACHHANG),
	FOREIGN KEY (MANHANVIEN) REFERENCES tbl_nhanvien(MANHANVIEN),
	FOREIGN KEY (MAPHONG) REFERENCES tbl_phong(MAPHONG)
)
GO
CREATE TABLE tbl_hoadon
(
	MAHOADON nVARCHAR(10) PRIMARY KEY,
	MAPHIEUTHUE nVARCHAR(10),
	MANHANVIEN nVARCHAR(10),
	MAKHACHHANG nVARCHAR(10),
	MAPHONG nVARCHAR(10),
	NGAYTHANHTOAN DATE,
	TIENPHONG MONEY,
	TINHTRANG NVARCHAR(50)  DEFAULT N'Chưa thanh toán'
	FOREIGN KEY (MAPHIEUTHUE) REFERENCES tbl_phieuthuephong(MAPHIEUTHUE)
)
GO
CREATE TABLE tbl_hoadondichvu
(
	MAHOADONDICHVU nVARCHAR(10) PRIMARY KEY,
	MAKHACHHANG nVARCHAR(10),
	THOIGIANLAP DATE,
	TONGTIENDICHVU MONEY,
)
GO
CREATE TABLE tbl_chitietdichvu
(
	MACHITIETDV  int unique identity(1,1) ,
	MAHOADONDICHVU nVARCHAR(10),
	MADICHVU nVARCHAR(10),
	GIADV MONEY,
	SOLUONG INT,
	TIENDICHVU MONEY
	PRIMARY KEY (MACHITIETDV),
	FOREIGN KEY (MAHOADONDICHVU) REFERENCES tbl_hoadondichvu(MAHOADONDICHVU),
	FOREIGN KEY (MADICHVU) REFERENCES tbl_dichvu(MADICHVU)
)
GO